# Generated by Django 3.0.4 on 2020-04-21 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200421_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 19, 23, 58, 568220)),
        ),
    ]
