# Generated by Django 2.2 on 2020-04-24 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200422_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 19, 32, 16, 858886)),
        ),
    ]
