# Generated by Django 2.2 on 2020-04-25 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200424_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 20, 34, 20, 707071)),
        ),
    ]
