# Generated by Django 3.0.4 on 2020-04-25 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200425_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 43, 51, 800533)),
        ),
    ]
