# Generated by Django 2.2 on 2020-04-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200426_0043'),
        ('core', '0004_auto_20200425_2034'),
    ]

    operations = [
    ]
